import React from 'react'


function items (){

    let productos = [
        {   id: 1,
            img: "https://essential.vtexassets.com/arquivos/ids/618203-1200-auto?v=637983163009170000&width=1200&height=auto&aspect=true",
            marca: 'REMERA NIKE AIR 1',  
            precio: 10.199,
            stock: 5,
            categoria: 'remeras',
        }, 
        {  
            id: 2,
            img:"https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dw304cfc30/AH6782_Z7F_20.jpg?impolicy=product&imwidth=915",
            marca: 'SWEATER DE HOMBRE EN LANA Y ALGODON',
            precio: 30.000,
            stock: 1,
            categoria: 'sweaters',
        },
        {   
            id: 3,
            img: "https://essential.vtexassets.com/arquivos/ids/591256-1200-auto?v=637937754092730000&width=1200&height=auto&aspect=true",
            marca: 'BUZO PUMA SWXP MEDIO CIERRE',  
            precio:  24.999,
            stock: 3,
            categoria: 'buzos',
        },
        {   id: 4, 
            img: "https://essential.vtexassets.com/arquivos/ids/563670-1200-auto?v=637895065203270000&width=1200&height=auto&aspect=true",
            marca: 'CAMPERA ADIDAS ORIGINALS ADICOLOR COLORBLOCK',
            precio: 32.999,
            stock: 9,
            categoria: 'camperas',
         },
        {   id: 5,
            img: "https://essential.vtexassets.com/arquivos/ids/592608-1200-auto?v=637938457447530000&width=1200&height=auto&aspect=true",
            marca: 'PANTALON NIKE CLUB',
            precio: 17.999,
            stock: 4,
            categoria: 'pantalones',
         },
        {   id: 6,
            img: "https://essential.vtexassets.com/arquivos/ids/616009-1200-auto?v=637980224405170000&width=1200&height=auto&aspect=true",
            marca: 'REMERA PUMA SUMMER',  
            precio: 7.499,
            stock: 6,
            categoria: 'remeras',
         }, 
         {   id: 7,
            img: "https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dw67d5d117/AF1414_166_24.jpg?imwidth=915&impolicy=product",
            marca: 'SWEATER DE MUJER CON CUELLO EN V', 
            precio: 30.000,
            stock: 12,
            categoria: 'sweaters',
         }, 
         {   id: 8,
            img: "https://essential.vtexassets.com/arquivos/ids/616039-1200-auto?v=637980224534200000&width=1200&height=auto&aspect=true",
            marca: 'BUZO ADIDAS ORIGINALS ADICOLOR ESSENTIALS',  
            precio: 18.999,
            stock: 3,
            categoria: 'buzos',
         }, 
         {   id: 9,
            img: "https://essential.vtexassets.com/arquivos/ids/553755-1200-auto?v=637871214930230000&width=1200&height=auto&aspect=true",
            marca: 'CAMPERA PUMA ICONIC T7',  
            precio: 17.249,
            stock: 8,
            categoria: 'camperas',
         },
         {   id: 10,
            img: "https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dw92cca52f/HF6081_6NM_20.jpg?imwidth=915&impolicy=product",
            marca: 'PANTALON DE MUJER LACOSTE',  
            precio: 12.000,
            stock: 7,
            categoria: 'pantalones',
         },  
         
         {   id: 11,
            img: "https://essential.vtexassets.com/arquivos/ids/622119-1200-auto?v=637988644140530000&width=1200&height=auto&aspect=true",
            marca: 'ZAPATILLAS PUMA MAYZE',  
            precio: 27.999,
            stock: 1,
            categoria: 'zapatillas',
         }, 
         {   id: 12,
            img: "https://drops-ba.com/wp-content/uploads/2022/09/adidas-Forum-Buckle-Low-Bad-Bunny-Blue-Tint.jpg",
            marca: 'ADIDAS FORUM BUCLE LOW BAD BUNNY BLUE TINT',  
            precio: 212.520,
            stock: 8,
            categoria: 'zapatillas',
         }, 
         {   id: 13,
            img: "https://drops-ba.com/wp-content/uploads/2022/03/Jordan-1-Low-Mocha.jpg",
            marca: 'JORDAN 1 LOW MOCHA',  
            precio: 95.700,
            stock: 3,
            categoria: 'zapatillas',
         },
         {   id: 14,
            img: 'https://drops-ba.com/wp-content/uploads/2021/09/Air-Jordan-1-Low-Black-Guava-Ice-W.jpg',
            marca: 'JORDAN 1 LOW BLACK GUAVA ICE',  
            precio: 101.640,
            stock: 7,
            categoria: 'zapatillas',
         },
         {   id: 15,
            img: 'https://drops-ba.com/wp-content/uploads/2022/07/Nike-Air-Force-1-Low-_07-White-W.jpg',
            marca: 'NIKE AIR FORCE 1 LOW 07 WHITE',
            precio: 61.600,
            stock: 2,
            categoria: 'zapatillas',
         },
         {   id: 16,
            img: 'https://drops-ba.com/wp-content/uploads/2022/08/adidas-Yeezy-Boost-350-V2-Sesame-2018-2022.jpg',
            marca: 'ADIDAS YEEZY BOOST 350 V2 SESAME (2018/2022)',  
            precio: 118.580,
            stock: 15,
            categoria: 'zapatillas',
         },
         {   id: 17,
            img: 'https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dw426c3aa3/42SFA0076_082_01.jpg?imwidth=915&impolicy=product',
            marca: 'ZAPATILLAS DE MUJER L--1 LACOSTE',  
            precio: 42.000,
            stock: 4,
            categoria: 'zapatillas',
         },
         {   id: 18,
            img: 'https://essential.vtexassets.com/arquivos/ids/613237-1200-auto?v=637974798979130000&width=1200&height=auto&aspect=true',
            marca: 'ZAPATILLAS PUMA KOSMOS RIDER',  
            precio: 27.999,
            stock: 7,
            categoria: 'zapatillas',
         },
         {   id: 19,
            img: 'https://drops-ba.com/wp-content/uploads/2022/05/adidas-Crazy-1-Lakers-Home.jpg',
            marca: 'ADIDAS CRAZY 1 LAKERS HOME',  
            precio: 135.520,
            stock: 5,
            categoria: 'zapatillas',
         },
         {   id: 20,
            img: 'https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dw75b53233/41CFA0054_21G_01.jpg?imwidth=915&impolicy=product',
            marca: 'ZAPATILLAS DE MUJER ZIANE PLUS LACOSTE',  
            precio: 34.000,
            stock: 2,
            categoria: 'zapatillas',
         }, 
         {   id: 21,
            img: 'https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dw8293ea0c/42SMA0092_2G1_01.jpg?imwidth=915&impolicy=product',
            marca: 'ZAPATILLAS DE HOMBRE L--1 LACOSTE',  
            precio: 42.000,
            stock: 6,
            categoria: 'zapatillas',
         }, 
         {   id: 22,
            img: 'https://drops-ba.com/wp-content/uploads/2022/05/Nike-Blazer-Low-sacai-British-Tan.jpg',
            marca: 'NIKE BLAZER LOW SACAI BRITISH TAN',
            precio: 60.060,
            stock: 4,
            categoria: 'zapatillas',
         }, 
    ]

    return(
        <>
            <img className='img_producto' src={productos.img}></img>
            <h3 className='detalle_producto'>{productos.marca}</h3>
            <p className='precio_producto'>{productos.precio}</p>
            <button className='btn btn-dark'>Más detalles</button>
        </>
    )
}